### ISSUE TITLE
First Release Checklist

### ISSUE THREAD

**Issue by silvester-pari** [EOEPCA/open-science-catalog-frontend#137]
## stability improvements
- [x] on the search page, the show/hide empty projects button does nothing
- [x] navigating to themes -> atmosphere and clicking submit on the pre-filled search box, the results are products
- [x] metrics - filtering by static and dynamic catalog returns different results
- [x] bbox search also adds bbox as query to call and breaking the query
- [x] metrics search menu is overlayed by table header
- [x] metrics - expanding certain items breaks the page (e.g. expand "biomass")
- [x] type "projects" actually returns products in search
- [x] page breaks if one item from static matching is 404
- [x] chips in search box overlay box border
- [x] some pages are empty (e.g. https://eoepca.github.io/open-science-catalog-frontend/projects/4d-earth-swarm),  link on project breadcrumb leads to empty project
- [ ] ~search: sometimes adding more filters returns more results~ this is the functionality of the q keyword
- [x] on certain screen widths, the dates in the project itemgrid have a line break
- [x] map sometimes does not fully load
- [x] pagination in itemgrid shows more pages than available
- [ ] ~hover over time range in metrics could show the actual values start/end for confirmation~ makes table laggy
- [x] individual coverages of a product could be better differentiable on a map if there are more of them (toggle off/on pointer or highlight on click of poi icon?), because if they are "almost similar" the center map move to action is hard to distinguish
- [x] on individual variables LINK button could be disabled if does not lead anywhere

## todos before first release
- [x] deployment setup (Dockerfile, env configuration etc.)
- [x] check all projects/products IDs working
- [x] backlink from products to projects
- [x] check on all screen sizes
- [x] check on all major browsers
- [x] host ~google fonts~ /material design icons locally
- [x] create flag to disable auth/login system (ideally do not even load auth if flag disables it?)
- [ ] ~terms & legal~ *skipping for v1.0 as no contribution feature yet*
- [ ] ~cookie notice?~ *skipping for v1.0 as no cookies are set yet*
- [x] create v1.0 tag and release note
